import { Venue, PlaybackState, EnvironmentData, Schedule, Track } from '@/types';

// ─── Demo Venues ────────────────────────────────────────────────

export const demoVenues: Venue[] = [
  {
    id: 'demo-1',
    organizationId: 'demo-org',
    name: 'Harmony Cafe',
    venueType: 'cafe',
    address: '123 Main Street',
    city: 'San Francisco',
    state: 'CA',
    country: 'US',
    latitude: 37.7749,
    longitude: -122.4194,
    timezone: 'America/Los_Angeles',
    status: 'active',
    createdAt: '2025-09-15T10:00:00Z',
    updatedAt: '2026-02-11T08:00:00Z',
    configuration: {
      id: 'demo-c1',
      venueId: 'demo-1',
      preferredGenres: ['jazz', 'lounge', 'ambient'],
      tempoRange: { min: 70, max: 110 },
      valenceRange: { min: 0.4, max: 0.7 },
      energyRange: { min: 0.3, max: 0.6 },
      volumeLevel: 45,
    },
  },
  {
    id: 'demo-2',
    organizationId: 'demo-org',
    name: 'Sunset Lounge',
    venueType: 'lounge',
    address: '456 Beach Avenue',
    city: 'Los Angeles',
    state: 'CA',
    country: 'US',
    latitude: 34.0522,
    longitude: -118.2437,
    timezone: 'America/Los_Angeles',
    status: 'active',
    createdAt: '2025-10-01T10:00:00Z',
    updatedAt: '2026-02-11T08:00:00Z',
    configuration: {
      id: 'demo-c2',
      venueId: 'demo-2',
      preferredGenres: ['electronic', 'deep house', 'chill'],
      tempoRange: { min: 100, max: 128 },
      valenceRange: { min: 0.5, max: 0.8 },
      energyRange: { min: 0.5, max: 0.8 },
      volumeLevel: 62,
    },
  },
  {
    id: 'demo-3',
    organizationId: 'demo-org',
    name: 'Tranquil Spa',
    venueType: 'spa',
    address: '789 Wellness Way',
    city: 'Seattle',
    state: 'WA',
    country: 'US',
    latitude: 47.6062,
    longitude: -122.3321,
    timezone: 'America/Los_Angeles',
    status: 'active',
    createdAt: '2025-10-20T10:00:00Z',
    updatedAt: '2026-02-11T08:00:00Z',
    configuration: {
      id: 'demo-c3',
      venueId: 'demo-3',
      preferredGenres: ['ambient', 'nature', 'meditation'],
      tempoRange: { min: 50, max: 80 },
      valenceRange: { min: 0.3, max: 0.6 },
      energyRange: { min: 0.1, max: 0.35 },
      volumeLevel: 28,
    },
  },
  {
    id: 'demo-4',
    organizationId: 'demo-org',
    name: 'Urban Bistro',
    venueType: 'restaurant',
    address: '321 Downtown Plaza',
    city: 'New York',
    state: 'NY',
    country: 'US',
    latitude: 40.7128,
    longitude: -74.0060,
    timezone: 'America/New_York',
    status: 'active',
    createdAt: '2025-11-05T10:00:00Z',
    updatedAt: '2026-02-11T08:00:00Z',
    configuration: {
      id: 'demo-c4',
      venueId: 'demo-4',
      preferredGenres: ['indie', 'acoustic', 'folk'],
      tempoRange: { min: 80, max: 120 },
      valenceRange: { min: 0.5, max: 0.8 },
      energyRange: { min: 0.3, max: 0.6 },
      volumeLevel: 38,
    },
  },
];

// ─── Demo Playback States ───────────────────────────────────────

export const demoPlaybackStates: Record<string, PlaybackState> = {
  'demo-1': {
    venueId: 'demo-1',
    isPlaying: false,
    currentTrack: {
      id: 'demo-track-1',
      title: 'Smooth Jazz Afternoon',
      genre: 'jazz',
      bpm: 95,
      key: 'C',
      valence: 0.6,
      energy: 0.4,
      duration: 245,
      generatedAt: '2026-02-11T10:00:00Z',
    },
    volume: 45,
  },
  'demo-2': {
    venueId: 'demo-2',
    isPlaying: false,
    currentTrack: {
      id: 'demo-track-2',
      title: 'Sunset Groove',
      genre: 'electronic',
      bpm: 118,
      key: 'Am',
      valence: 0.7,
      energy: 0.6,
      duration: 312,
      generatedAt: '2026-02-11T10:15:00Z',
    },
    volume: 62,
  },
  'demo-3': {
    venueId: 'demo-3',
    isPlaying: false,
    currentTrack: {
      id: 'demo-track-3',
      title: 'Ocean Meditation',
      genre: 'ambient',
      bpm: 60,
      key: 'G',
      valence: 0.4,
      energy: 0.2,
      duration: 420,
      generatedAt: '2026-02-11T10:30:00Z',
    },
    volume: 28,
  },
  'demo-4': {
    venueId: 'demo-4',
    isPlaying: false,
    currentTrack: {
      id: 'demo-track-4',
      title: 'Acoustic Memories',
      genre: 'folk',
      bpm: 105,
      key: 'D',
      valence: 0.65,
      energy: 0.45,
      duration: 198,
      generatedAt: '2026-02-11T10:45:00Z',
    },
    volume: 38,
  },
};

// ─── Demo Environment Data ──────────────────────────────────────

export const demoEnvironmentData: Record<string, EnvironmentData> = {
  'demo-1': {
    venueId: 'demo-1',
    timestamp: '2026-02-11T14:30:00Z',
    temperature: 21.5,
    humidity: 44,
    weatherCondition: 'partly cloudy',
    ambientLight: 32,
    crowdDensity: 58,
  },
  'demo-2': {
    venueId: 'demo-2',
    timestamp: '2026-02-11T14:30:00Z',
    temperature: 23.2,
    humidity: 38,
    weatherCondition: 'clear',
    ambientLight: 18,
    crowdDensity: 72,
  },
  'demo-3': {
    venueId: 'demo-3',
    timestamp: '2026-02-11T14:30:00Z',
    temperature: 22.8,
    humidity: 48,
    weatherCondition: 'clear',
    ambientLight: 12,
    crowdDensity: 35,
  },
  'demo-4': {
    venueId: 'demo-4',
    timestamp: '2026-02-11T14:30:00Z',
    temperature: 20.1,
    humidity: 41,
    weatherCondition: 'partly cloudy',
    ambientLight: 68,
    crowdDensity: 48,
  },
};

// ─── Demo Schedules ─────────────────────────────────────────────

export const demoSchedules: Schedule[] = [
  {
    id: 'demo-s1',
    venueId: 'demo-1',
    name: 'Morning Calm',
    dayOfWeek: [1, 2, 3, 4, 5],
    startTime: '08:00',
    endTime: '12:00',
    genres: ['ambient', 'jazz'],
    tempoRange: { min: 60, max: 90 },
    energyRange: { min: 0.2, max: 0.4 },
    isActive: true,
  },
  {
    id: 'demo-s2',
    venueId: 'demo-1',
    name: 'Afternoon Vibes',
    dayOfWeek: [1, 2, 3, 4, 5],
    startTime: '12:00',
    endTime: '17:00',
    genres: ['lounge', 'jazz'],
    tempoRange: { min: 80, max: 110 },
    energyRange: { min: 0.4, max: 0.6 },
    isActive: true,
  },
  {
    id: 'demo-s3',
    venueId: 'demo-2',
    name: 'Sunset Session',
    dayOfWeek: [4, 5, 6],
    startTime: '16:00',
    endTime: '20:00',
    genres: ['chill', 'deep house'],
    tempoRange: { min: 100, max: 120 },
    energyRange: { min: 0.4, max: 0.6 },
    isActive: true,
  },
];

// ─── Demo Tracks ────────────────────────────────────────────────

export const demoTracks: Track[] = [
  {
    id: 'demo-track-1',
    title: 'Smooth Jazz Afternoon',
    genre: 'jazz',
    bpm: 95,
    key: 'C',
    valence: 0.6,
    energy: 0.4,
    duration: 245,
    generatedAt: '2026-02-11T10:00:00Z',
  },
  {
    id: 'demo-track-2',
    title: 'Sunset Groove',
    genre: 'electronic',
    bpm: 118,
    key: 'Am',
    valence: 0.7,
    energy: 0.6,
    duration: 312,
    generatedAt: '2026-02-11T10:15:00Z',
  },
  {
    id: 'demo-track-3',
    title: 'Ocean Meditation',
    genre: 'ambient',
    bpm: 60,
    key: 'G',
    valence: 0.4,
    energy: 0.2,
    duration: 420,
    generatedAt: '2026-02-11T10:30:00Z',
  },
  {
    id: 'demo-track-4',
    title: 'Acoustic Memories',
    genre: 'folk',
    bpm: 105,
    key: 'D',
    valence: 0.65,
    energy: 0.45,
    duration: 198,
    generatedAt: '2026-02-11T10:45:00Z',
  },
  {
    id: 'demo-track-5',
    title: 'Lounge Paradise',
    genre: 'lounge',
    bpm: 88,
    key: 'F',
    valence: 0.55,
    energy: 0.35,
    duration: 278,
    generatedAt: '2026-02-11T11:00:00Z',
  },
];
